### ISSUE TITLE
Multipart Form Logging

### ISSUE THREAD

**Issue by Vyazovoy** [AFNetworking/AFHTTPRequestOperationLogger#13]
Nice logger but:
when I try to send multipart request with Debug level of logging I can't see content of body (because used stream). Can you fix this behavior? Or it is not a bag?

**Comment by mattt** [comment]
There are a few reasons why it would be difficult to get a reasonable output for multipart requests.

First, logging the entire multipart request body for any significant payload would flood `STDOUT` with a wall of meaningless binary (though, this may be desirable for the most explicit level of logging). It's not entirely clear what would be a better alternative to this.

Second, and more importantly, because `AFHTTPClient` was refactored as of 1.0 to use a custom input stream for the body, it would be tricky to rewind the stream to get at the contents in a way that didn't interfere with sending the original request. Or at least, this isn't something that I'm entirely keen to put time into now, so feel free to tackle that if you feel so inclined.
